### ISSUE TITLE
Target the active camera component, not the `<a-camera>` wrapper

### ISSUE THREAD

**Issue by ngokevin** [IagoLast/totem#1]
In newer A-Frame, you can use the scene to grab the active camera.

In case people have `<a-entity camera>`

**Comment by IagoLast** [comment]
What about using a parameter?

something like:
`
<a-entity totem="camera: #selector ...>
`

Maybe this approach gives more flexibility, what do you think? @ngokevin

**Comment by ngokevin** [comment]
Seems to make sense only to grab the active camera, which can be deduced, and have it just work.

**Comment by IagoLast** [comment]
@ngokevin feel free to review and comment the PR
